name: Deploy app to Heroku

on:
  push:	
    paths:
      - ".github/workflows/heroku-deploy.yml"
      - "src/**"
      - ".dockerignore"
      - ".gitignore"
      - "Dockerfile"
      - "heroku.yml"
      - "package.json"
      - "package-lock.json"
      - 'README.md'
      - 'requirements.txt'
      - 'tailwind.config.json'
    branches:	
      - main
  pull_request:	
    branches:	
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Build the image to Container Registry
        env:
          APP_NAME: ${{ 'itproger-learning-django' }}
        run: docker build -t registry.heroku.com/$APP_NAME/web .
      
      - name: Push the image to Container Registry
        env:
          APP_NAME: ${{ 'itproger-learning-django' }}
        run: docker build -t registry.heroku.com/$APP_NAME/web .

      - name: Release the image
        env:
          APP_NAME: ${{ 'itproger-learning-django' }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a $APP_NAME
